In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
c=load_breast_cancer()

In [ ]:
a={
    "name":"Alice",
    "id":47001
}
a

{'name': 'Alice', 'id': 47001}

In [ ]:
c.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
c.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
c.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
c.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
df=pd.DataFrame(np.c_[c.data,c.target],columns=list(c.feature_names)+["output"])
df

     mean radius  mean texture  ...  worst fractal dimension  output
0          17.99         10.38  ...                  0.11890     0.0
1          20.57         17.77  ...                  0.08902     0.0
2          19.69         21.25  ...                  0.08758     0.0
3          11.42         20.38  ...                  0.17300     0.0
4          20.29         14.34  ...                  0.07678     0.0
..           ...           ...  ...                      ...     ...
564        21.56         22.39  ...                  0.07115     0.0
565        20.13         28.25  ...                  0.06637     0.0
566        16.60         28.08  ...                  0.07820     0.0
567        20.60         29.33  ...                  0.12400     0.0
568         7.76         24.54  ...                  0.07039     1.0

[569 rows x 31 columns]

In [ ]:
df.shape

(569, 31)

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
cat_col=df.select_dtypes(include=["object"]).columns.tolist()
cat_col

[]

In [ ]:
x=df.iloc[:,:-1]

In [ ]:
x.shape

(569, 30)

In [ ]:
x

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: output, Length: 569, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=41)

In [ ]:
x_train

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
475        12.83         15.73  ...          0.3006                  0.07802
298        14.26         18.17  ...          0.2636                  0.07676
220        13.65         13.16  ...          0.2380                  0.08718
549        10.82         24.21  ...          0.3059                  0.07626
567        20.60         29.33  ...          0.4087                  0.12400
..           ...           ...  ...             ...                      ...
469        11.62         18.18  ...          0.2660                  0.09270
407        12.85         21.37  ...          0.2488                  0.08151
243        13.75         23.77  ...          0.2663                  0.06321
321        20.16         19.66  ...          0.3055                  0.05933
80         11.45         20.97  ...          0.2762                  0.08851

[455 rows x 30 columns]

In [ ]:
x_train.shape

(455, 30)

In [ ]:
y_train.shape

(455,)

In [ ]:
x_test.shape

(114, 30)

In [ ]:
y_test.shape

(114,)

In [ ]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [ ]:
std=StandardScaler()
mm=MinMaxScaler()

In [ ]:
x_train_std_sc_data=std.fit_transform(x_train)
x_train_std_sc_data

array([[-0.36498729, -0.83463794, -0.37044213, ..., -0.25967334,
         0.17192889, -0.3532633 ],
       [ 0.05208811, -0.26700868, -0.01772895, ..., -0.60430302,
        -0.44112743, -0.4234167 ],
       [-0.12582517, -1.43250975, -0.15915297, ..., -0.52384354,
        -0.86529613,  0.15674078],
       ...,
       [-0.09665906,  1.03574702, -0.1312069 , ..., -0.82212489,
        -0.39639089, -1.17784414],
       [ 1.77288871,  0.07961739,  1.6708907 , ...,  0.4236204 ,
         0.25311743, -1.39387207],
       [-0.76747963,  0.38436917, -0.75491221, ..., -0.81891263,
        -0.2323569 ,  0.23079159]])

In [ ]:
employees = {
  "emp_id": [12000, 12001, 12002, 12003, 12004, 12005, 12006, 12007, 12008, 12009],
  "emp_name": ["Sara", "Laura", "Bryan", "John", "Maria", "David", "Emily", "Michael", "Jessica", "Daniel"],
  "salary": [60000, 75000, 50000, 90000, 62000, 80000, 58000, 70000, 65000, 85000],
  "feedback": [
    "Excellent team player.",
    "Consistently meets targets.",
    "Needs to improve communication skills.",
    "Highly innovative and proactive.",
    "Good analytical skills.",
    "Strong leadership potential.",
    "Reliable and detail-oriented.",
    "Problem-solver, but sometimes slow.",
    "Collaborative and supportive.",
    "Exceptional technical skills."
  ]
}

In [ ]:
df1=pd.DataFrame(employees)
df1

   emp_id emp_name  salary                                feedback
0   12000     Sara   60000                  Excellent team player.
1   12001    Laura   75000             Consistently meets targets.
2   12002    Bryan   50000  Needs to improve communication skills.
3   12003     John   90000        Highly innovative and proactive.
4   12004    Maria   62000                 Good analytical skills.
5   12005    David   80000            Strong leadership potential.
6   12006    Emily   58000           Reliable and detail-oriented.
7   12007  Michael   70000     Problem-solver, but sometimes slow.
8   12008  Jessica   65000           Collaborative and supportive.
9   12009   Daniel   85000           Exceptional technical skills.

In [ ]:
df1["emp_name"].value_counts()

emp_name
Sara       1
Laura      1
Bryan      1
John       1
Maria      1
David      1
Emily      1
Michael    1
Jessica    1
Daniel     1
Name: count, dtype: int64

In [ ]:
df1["feedback"].value_counts()

feedback
Excellent team player.                    1
Consistently meets targets.               1
Needs to improve communication skills.    1
Highly innovative and proactive.          1
Good analytical skills.                   1
Strong leadership potential.              1
Reliable and detail-oriented.             1
Problem-solver, but sometimes slow.       1
Collaborative and supportive.             1
Exceptional technical skills.             1
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
One=OneHotEncoder(sparse_output=False)
L=LabelEncoder()

In [ ]:
df1['feedback']=L.fit_transform(df1['feedback'])
df1

   emp_id emp_name  salary  feedback
0   12000     Sara   60000         2
1   12001    Laura   75000         1
2   12002    Bryan   50000         6
3   12003     John   90000         5
4   12004    Maria   62000         4
5   12005    David   80000         9
6   12006    Emily   58000         8
7   12007  Michael   70000         7
8   12008  Jessica   65000         0
9   12009   Daniel   85000         3

In [ ]:
a=One.fit_transform(df1[["emp_name"]])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
df1_enc=pd.DataFrame(a,columns=One.get_feature_names_out())
df1_enc

   emp_name_Bryan  emp_name_Daniel  ...  emp_name_Michael  emp_name_Sara
0             0.0              0.0  ...               0.0            1.0
1             0.0              0.0  ...               0.0            0.0
2             1.0              0.0  ...               0.0            0.0
3             0.0              0.0  ...               0.0            0.0
4             0.0              0.0  ...               0.0            0.0
5             0.0              0.0  ...               0.0            0.0
6             0.0              0.0  ...               0.0            0.0
7             0.0              0.0  ...               1.0            0.0
8             0.0              0.0  ...               0.0            0.0
9             0.0              1.0  ...               0.0            0.0

[10 rows x 10 columns]

In [ ]:
df1_new=pd.concat([df1,df1_enc],axis=1)

In [ ]:
df1_new

   emp_id emp_name  salary  ...  emp_name_Maria  emp_name_Michael  emp_name_Sara
0   12000     Sara   60000  ...             0.0               0.0            1.0
1   12001    Laura   75000  ...             0.0               0.0            0.0
2   12002    Bryan   50000  ...             0.0               0.0            0.0
3   12003     John   90000  ...             0.0               0.0            0.0
4   12004    Maria   62000  ...             1.0               0.0            0.0
5   12005    David   80000  ...             0.0               0.0            0.0
6   12006    Emily   58000  ...             0.0               0.0            0.0
7   12007  Michael   70000  ...             0.0               1.0            0.0
8   12008  Jessica   65000  ...             0.0               0.0            0.0
9   12009   Daniel   85000  ...             0.0               0.0            0.0

[10 rows x 14 columns]

In [ ]:
df1_new.drop("emp_name",axis=1,inplace=True)
df1_new

   emp_id  salary  feedback  ...  emp_name_Maria  emp_name_Michael  emp_name_Sara
0   12000   60000         2  ...             0.0               0.0            1.0
1   12001   75000         1  ...             0.0               0.0            0.0
2   12002   50000         6  ...             0.0               0.0            0.0
3   12003   90000         5  ...             0.0               0.0            0.0
4   12004   62000         4  ...             1.0               0.0            0.0
5   12005   80000         9  ...             0.0               0.0            0.0
6   12006   58000         8  ...             0.0               0.0            0.0
7   12007   70000         7  ...             0.0               1.0            0.0
8   12008   65000         0  ...             0.0               0.0            0.0
9   12009   85000         3  ...             0.0               0.0            0.0

[10 rows x 13 columns]